<h1><?php echo $this->hyperlink($this->setting('installation_title', 'Omeka S'), $this->url('top', ['action' => 'index'])); ?></h1>
<h2><?php echo $this->translate('Search'); ?></h2>

<?php echo $this->partial(
  'omeka/search/form.phtml',
  [
      'fulltextSearch' => $this->escapeHtml($this->params()->fromQuery('fulltext_search')),
      'action' => 'results',
      'submitLabel' => $this->translate('Search')
  ]
); ?>
