<?php 
$fulltextSearch = $this->params()->fromQuery('fulltext_search'); 
$this->headLink()->prependStylesheet($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.jquery.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
?>

<h1><?php echo $this->hyperlink($this->setting('installation_title', 'Omeka S'), $this->url('top', ['action' => 'index'])); ?></h1>

<?php echo $this->partial(
  'omeka/search/form.phtml',
  [
      'fulltextSearch' => $this->escapeHtml($this->params()->fromQuery('fulltext_search')),
      'submitLabel' => $this->translate('Search site pages')
  ]
); ?>

<h2><?php echo sprintf($this->translate('Site page results for "%s"'), $fulltextSearch); ?></h2>

<?php echo $this->pagination(); ?>

<?php if (count($sitePages) > 0): ?>
<div class="site-results">
    <table class="tablesaw" data-tablesaw-mode="stack">
      <thead>
          <tr>
              <th><?php echo $this->translate('Page title'); ?></th>
              <th><?php echo $this->translate('Site title'); ?></th>
          </tr>
      </thead>
      <tbody>
        <?php foreach ($sitePages as $sitePage): ?>
        <?php $site = $sitePage->site(); ?>
        <tr>
            <td><?php echo $this->hyperlink($sitePage->title(), $sitePage->siteUrl()); ?></td>
            <td><?php echo $this->hyperlink($site->title(), $site->siteUrl()); ?></td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table></div>

<?php echo $this->pagination(); ?>
<?php endif; ?>

<script>
  jQuery(document).trigger('enhance.tablesaw');
</script>
