<?php
$translate = $this->plugin('translate');

$this->htmlElement('body')->appendAttribute('class', 'site browse front');
$title = $this->setting('installation_title', 'Omeka S');
$subtitle = $translate('Sites');
$this->headTitle($subtitle);
?>
<h1><?php echo $this->hyperlink($title, $this->url('top', ['action' => 'index'])); ?></h1>

<?php if ($sites): ?>

<?php echo $this->partial(
  'omeka/search/form.phtml',
  [
      'fulltextSearch' => $this->escapeHtml($this->params()->fromQuery('fulltext_search')),
      'action' => $this->escapeHtml($this->url('search', ['action' => 'results']))
  ]
); ?>

<h2 class="site-list-heading"><?php echo $subtitle; ?></h2>

<div class="site-list">
<?php
foreach ($sites as $site):
    echo $this->partial('common/site-list-entry', ['site' => $site, 'showSummary' => true]);
endforeach;
?>
</div>

<?php echo $this->pagination(); ?>

<?php endif; ?>
<p><?php echo sprintf(
    $translate('Go to the %1$s to start working with %2$s.'),
    $this->hyperlink($translate('Admin dashboard'), $this->url('admin')),
    $title
); ?></p>
